---
version: "3.7"

# This docker-compose file is used to build and test the container

secrets:
  database_creds:
    file: ./src/secrets/database_creds.yml

services:
  trustymail_reporter:
    # Run the container normally
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    image: cisagov/trustymail_reporter
    init: true
    restart: "no"
    secrets:
      - source: database_creds
        target: database_creds.yml
  redis:
    image: redis:alpine
